template = ""
rev_id = 312
template_sha = "aaa43738ed413bb95e9bd39f5489b35bab88cc4b"

[replacements]
__GLOTTOLOG_ID__ = "wasc1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wac"
__UND2C__ = "wac"
__UNDEFINED__ = "Wasco-Wishram"
__UND__ = "wac"
