template = ""
rev_id = 318
template_sha = "71a1af4cb1cb80e9b86b2e9d1c090f473b0d8270"

[replacements]
__GLOTTOLOG_ID__ = "wasc1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wac"
__UND2C__ = "wac"
__UNDEFINED__ = "Wasco-Wishram"
__UND__ = "wac"
