template = ""
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "wasc1239"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wac"
__UND2C__ = "wac"
__UNDEFINED__ = "Wasco-Wishram"
__UND__ = "wac"
